linear_velocity_controller:
  ros__parameters:
    # Controller type
    type: linear_velocity_controller/LinearVelocityController

    # Controller-specific parameters
    y_vel: 0.1
    y_dist: 0.1
    