services:

  touch_detection_recording:
    image: touch_detection_recording
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}

    # Set a suitable container name
    container_name: touch_detection_recording

    network_mode: "host"
    ipc: "host"
    privileged: true
    tty: true
    stdin_open: true

    volumes:
      # Allow graphical programs in the container
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
      # Shared memory (to allow communication with other ROS processes on host PC)
      - /dev/shm:/dev/shm
    
    environment:
      # Allow graphical programs in the container
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      # Allow colorized console output
      RCUTILS_COLORIZED_OUTPUT: 1
      # Other variables (can be overridden in other compose files)
      ROS_DOMAIN_ID: 40


    # When the container is started with docker compose up, it will sleep indefinitely to keep the container alive
    command: sleep infinity
